const fs = require('fs');
const path = require('path');
const Governor = require('../index.js');

async function generateBacklog() {
    console.log("Starting Vision-to-Action Analysis...");
    
    const workspaceRoot = process.cwd(); 
    const memoryPath = path.join(workspaceRoot, 'MEMORY.md');
    const soulPath = path.join(workspaceRoot, 'SOUL.md');
    
    if (!fs.existsSync(memoryPath) || !fs.existsSync(soulPath)) {
        console.error("Critical mission files (MEMORY.md/SOUL.md) missing.");
        return;
    }

    // Example tactical alignments - In the future, this will be dynamically generated by the agent
    const alignments = [
        {
            title: "TECH-004: Implement rolling window TPM monitoring",
            priority: "high",
            description: "Refactor Governor to use a precise token-per-minute window instead of just requests per minute."
        },
        {
            title: "DOC-002: Align AGENTS.md with SOUL.md legacy",
            priority: "medium",
            description: "Ensure AGENTS.md explicitly references the 'Zown' gamer legacy and raid-leader tone."
        }
    ];

    const governor = new Governor();
    for (const task of alignments) {
        const result = governor.addTask(task.title, task.priority, task.description);
        console.log(`Generated Ticket: ${result.id} - ${result.title}`);
    }
}

module.exports = generateBacklog;

if (require.main === module) {
    generateBacklog().catch(console.error);
}
